spring:
  datasource:
    url: jdbc:mysql://192.168.56.10/gulimall_sms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  application:
    name: mall-product
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000